@startuml Manage Booking (GET All)

footer Page %page% of %lastpage%
title "Manage Booking (GET All)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:bookings" as routerBookings
participant "<<controllers>>\n:bookings" as controllersBookings
participant "<<model>>\n:Booking" as modelBooking
database "<<MongoDB>>\n:bookings" as BookingsDatabase

client->server ++:req.get('/bookings')
server->routerBookings ++:app.use('/bookings',bookings)
routerBookings -> controllersBookings ++:getBookings(req.user)
controllersBookings->modelBooking ++:getAll(req.user)
modelBooking ->BookingsDatabase ++: find({user:req.user.id})
BookingsDatabase --> modelBooking --: bookings
controllersBookings <-- modelBooking --:bookings
controllersBookings->client --:response

@enduml
